databases:
  - name: todo-db
    databaseName: todo_list_production
    user: todo_user
    region: oregon
    plan: free

services:
  - type: web
    name: todo-list-app
    runtime: node
    region: oregon
    plan: free
    branch: main
    
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_PORT
        value: "5432"
