databases:
  - name: todo-db
    databaseName: todo_list_production
    user: todo_user
    region: oregon
    plan: free

services:
  - type: web
    name: todo-list-app
    runtime: node
    region: oregon
    plan: free
    branch: main
    
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_PORT
        value: "5432"
    
    initialDeployHook: |
      echo "Initializing database..."
      export PGPASSWORD="$DB_PASSWORD"
      psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" << 'EOF'
      CREATE TABLE IF NOT EXISTS items (
        id SERIAL PRIMARY KEY,
        title VARCHAR(200) NOT NULL
      );
      
      INSERT INTO items (title) 
      SELECT unnest(ARRAY['Buy milk', 'Finish homework'])
      WHERE NOT EXISTS (SELECT 1 FROM items LIMIT 1);
      EOF
      echo "Database initialization complete!"
