# render.yaml
databases:
  - name: todo-db
    databaseName: todo_list_production
    user: todo_user
    region: oregon
    plan: free
    postgresMajorVersion: 15

services:
  - type: web
    name: todo-list-app
    runtime: node
    region: oregon
    plan: free
    branch: main
    
    # Build and start commands
    buildCommand: npm install
    startCommand: npm start
    
    # Health check endpoint (you'll need to add this)
    healthCheckPath: /health
    
    # Auto-deploy on push
    autoDeploy: true
    
    # Environment variables
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      
      # Database connection - using individual variables as per your code
      - key: DB_HOST
        fromDatabase:
          name: todo-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: todo-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: todo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: todo-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: todo-db
          property: port
    
    # Initialize database with your schema
    initialDeployHook: |
      echo "Setting up database..."
      PGPASSWORD=$DB_PASSWORD psql -h $DB_HOST -p $DB_PORT -U $DB_USER -d $DB_NAME -c "
      CREATE TABLE IF NOT EXISTS items (
        id SERIAL PRIMARY KEY,
        title VARCHAR(200) NOT NULL
      );
      
      INSERT INTO items (title) 
      SELECT * FROM (VALUES ('Buy milk'), ('Finish homework')) AS v(title)
      WHERE NOT EXISTS (SELECT 1 FROM items LIMIT 1);
      "
      echo "Database setup complete!"
